 # Vehiculo
 mi_vehiculo = Vehiculo()
 mi_vehiculo.set_nombre_vehiculo("El Gran Vehiculo")
 print("Usando miVehiculo, nombreVehiculo:", mi_vehiculo.get_nombre_vehiculo())
 print("Usando miVehiculo llama a:", mi_vehiculo.transportar())
 print()
 # Acuatico
 mi_acuatico = Acuatico()
 mi_acuatico.set_nombre_vehiculo("El Acuático")
 print("Usando miAcuatico, nombreVehiculo:", mi_acuatico.get_nombre_vehiculo())
 print("Usando miAcuatico llama a:", mi_acuatico.transportar())
 print("Usando miAcuatico llama a:", mi_acuatico.navegar())
 print()
 # Barco
 mi_barco = Barco()
 mi_barco.set_nombre_vehiculo("Titanic")
 print("Usando miBarco, nombreVehiculo:", mi_barco.get_nombre_vehiculo())
 print("Usando miBarco llama a:", mi_barco.transportar())
 print("Usando miBarco llama a:", mi_barco.navegar())
 print("Usando miBarco llama a:", mi_barco.prender_motor())
 print()
 # Velero
 mi_velero = Velero()
 mi_velero.set_nombre_vehiculo("Veleron")
 print("Usando miVelero, nombreVehiculo:", mi_velero.get_nombre_vehiculo())
 print("Usando miVelero llama a:", mi_velero.transportar())
 print("Usando miVelero llama a:", mi_velero.navegar())
 print("Usando miVelero llama a:", mi_velero.izar_velas())
 print()
 # Aereo
 mi_aereo = Aereo()
 mi_aereo.set_nombre_vehiculo("El Aereo")
 print("Usando miAereo, nombreVehiculo:", mi_aereo.get_nombre_vehiculo())
 print("Usando miAereo llama a:", mi_aereo.transportar())
 print("Usando miAereo llama a:", mi_aereo.volar())
 print()
 # Avion
 mi_avion = Avion()
 mi_avion.set_nombre_vehiculo("El Condor")
 print("Usando miAvion, nombreVehiculo:", mi_avion.get_nombre_vehiculo())
 print("Usando miAvion llama a:", mi_avion.transportar())
 print("Usando miAvion llama a:", mi_avion.volar())
 print("Usando miAvion llama a:", mi_avion.bajar_tren_de_aterrizaje())
 print()
 # Helicoptero
 mi_helicoptero = Helicoptero()
 mi_helicoptero.set_nombre_vehiculo("El Lobo del Aire")
 print("Usando miHelicoptero, nombreVehiculo:", mi_helicoptero.get_nombre_vehiculo())
 print("Usando miHelicoptero llama a:", mi_helicoptero.transportar())
 print("Usando miHelicoptero llama a:", mi_helicoptero.volar())
 print("Usando miHelicoptero llama a:", mi_helicoptero.encender_helices())
 print()
 # Listado final
 print("Nombre Vehiculo:", mi_vehiculo.get_nombre_vehiculo())
 print("Nombre Acuatico:", mi_acuatico.get_nombre_vehiculo())
 print("Nombre Aereo:", mi_aereo.get_nombre_vehiculo())
 print("Nombre Barco:", mi_barco.get_nombre_vehiculo())
 print("Nombre Velero:", mi_velero.get_nombre_vehiculo())
 print("Nombre Avion:", mi_avion.get_nombre_vehiculo())
 print("Nombre Helicoptero:", mi_helicoptero.get_nombre_vehiculo())